dist: focal
language: python
python:
  - "3.10"
# Install dependencies
env:
  global:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
    - COVERALLS_SERVICE_NAME=coveralls-python
before_install:
  - cd eventsphere
install:
  - pip install -r requirements.txt
# Run format and lint checks
script:
  - black --check .
  - flake8 .
  - coverage run manage.py test
  - coverage report
after_success:
  - coveralls --verbose
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACS_KEY
  secret_access_key: $AWS_SCRT_KEY
  region: us-west-2
  app: eventsphere
  env: eventsphere-env2
  bucket_name: 'elasticbeanstalk-us-east-1-626635433032'
  on:
    repo: gcivil-nyu-org/wed-fall24-team3
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(staging|main)$
#    branches:
#        - main
#        - staging