dist: focal
language: python
python:
  - "3.11"
# Install dependencies
env:
  global:
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
    - COVERALLS_SERVICE_NAME=coveralls-python
before_install:
  - cd eventsphere
install:
  - pip install -r requirements.txt
# Run format and lint checks
script:
  - black --check .
  - flake8 .
  - coverage run --parallel-mode --concurrency=multiprocessing manage.py test --parallel
  - coverage combine && coverage report
after_success:
  - coveralls --verbose
#before_deploy:
#  - echo "Deploying to Elastic Beanstalk environment for branch: $TRAVIS_BRANCH"
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACS_KEY
    secret_access_key: $AWS_SCRT_KEY
    region: us-west-2
    app: eventsphere
    env: eventsphere-env2
    bucket_name: 'elasticbeanstalk-us-west-2-626635433032'
    on:
      branch: staging
      repo: gcivil-nyu-org/wed-fall24-team3
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACS_KEY
    secret_access_key: $AWS_SCRT_KEY
    region: us-west-2
    app: production
    env: prod-env
    bucket_name: 'elasticbeanstalk-us-west-2-626635433032'
    on:
      branch: main
      repo: gcivil-nyu-org/wed-fall24-team3