[tool.black]
line-length = 88
target-version = ['py39']
exclude = 'migrations*'

[tool.coverage.report]
omit = [
    "*/tests/*",
    "*/migrations/*",
    "manage.py",
    "eventsphere/urls.py",
    "events/urls.py",
    "**/__init__.py"
]