# Generated by Django 5.1.2 on 2024-10-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_numtickets_creatorprofile_event_created_by"),
        ("events", "0007_event_category_event_image_url"),
    ]

    operations = []
