# Generated by Django 5.1.2 on 2024-10-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_merge_20241029_0323"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticketsSold",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
