# Generated by Django 5.1.2 on 2024-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_ticketssold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticketsSold",
            field=models.IntegerField(default=0),
        ),
    ]
