# Generated by Django 5.1.1 on 2024-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_ticket_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorprofile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="creatorprofile",
            name="organisation",
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="contact_number",
            field=models.CharField(default="N/A", max_length=20),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="organization_email",
            field=models.EmailField(default="def@se.com", max_length=254),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="organization_name",
            field=models.CharField(default="NYU", max_length=255),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="organization_social_media",
            field=models.URLField(blank=True, null=True),
        ),
    ]
