# Generated by Django 5.1.1 on 2024-11-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_chatroom_chatmessage_roommember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
