# Generated by Django 5.1.1 on 2024-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_ticket_email_alter_ticket_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
