# Generated by Django 5.1.2 on 2024-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.TextField(default="message"),
        ),
    ]
