# Generated by Django 5.1.2 on 2024-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sub_title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="New Message", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.TextField(default="chat_message"),
        ),
    ]
